spring: 
  datasource: 
    url:  jdbc:mysql://localhost:3306/springbootfirst
    username: root
    password: root
    driverClassName: com.mysql.jdbc.Driver
    max-active: 20
    max-idle: 8
    min-idle: 8
    initial-size: 10
  jpa: 
    show-sql: true
    hibernate: 
      ddl-auto: update
  thymeleaf: 
    cache: false

server: 
  port: 8888
#logging: 
#  level: 
#    root: INFO
#    org: 
#      springframework: 
#        web: INFO
#      hibernate: INFO